//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_resolucion_formulario_det
    {
        public decimal IdResolucion { get; set; }
        public int secuencia { get; set; }
        public decimal IdPregunta { get; set; }
        public Nullable<double> re_ponderacion { get; set; }
    
        public virtual enc_formulario_pregunta enc_formulario_pregunta { get; set; }
        public virtual enc_resolucion_formulario enc_resolucion_formulario { get; set; }
    }
}
