//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_resolucion_formulario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enc_resolucion_formulario()
        {
            this.enc_resolucion_formulario_det = new HashSet<enc_resolucion_formulario_det>();
        }
    
        public decimal IdResolucion { get; set; }
        public int IdPeriodo { get; set; }
        public decimal IdEmpleado { get; set; }
        public decimal IdEmpleado_evaluado { get; set; }
        public System.DateTime re_fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enc_resolucion_formulario_det> enc_resolucion_formulario_det { get; set; }
        public virtual tbl_periodo_evaluacion tbl_periodo_evaluacion { get; set; }
        public virtual rol_empleado rol_empleado { get; set; }
    }
}
