//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class enc_resolucion_calificacion
    {
        public decimal IdEmpleado { get; set; }
        public int IdPeriodo { get; set; }
        public double Calificacion { get; set; }
        public bool factor_cumplimiento { get; set; }
        public double calificacion_final { get; set; }
    
        public virtual tbl_periodo_evaluacion tbl_periodo_evaluacion { get; set; }
        public virtual rol_empleado rol_empleado { get; set; }
    }
}
