//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities_general : DbContext
    {
        public Entities_general()
            : base("name=Entities_general")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enc_formulario> enc_formulario { get; set; }
        public virtual DbSet<enc_formulario_pregunta> enc_formulario_pregunta { get; set; }
        public virtual DbSet<enc_resolucion_formulario> enc_resolucion_formulario { get; set; }
        public virtual DbSet<enc_resolucion_formulario_det> enc_resolucion_formulario_det { get; set; }
        public virtual DbSet<rol_cargo> rol_cargo { get; set; }
        public virtual DbSet<rol_empleado> rol_empleado { get; set; }
        public virtual DbSet<rol_empleado_x_correo_x_periodo> rol_empleado_x_correo_x_periodo { get; set; }
        public virtual DbSet<tbl_parametros_correo> tbl_parametros_correo { get; set; }
        public virtual DbSet<tbl_periodo_evaluacion> tbl_periodo_evaluacion { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<rol_empleado_x_formulario> rol_empleado_x_formulario { get; set; }
        public virtual DbSet<enc_resolucion_calificacion> enc_resolucion_calificacion { get; set; }
        public virtual DbSet<vw_reporte002> vw_reporte002 { get; set; }
        public virtual DbSet<vw_reporte003> vw_reporte003 { get; set; }
    
        public virtual int sp_cerrar_periodo(Nullable<int> idPeriodo)
        {
            var idPeriodoParameter = idPeriodo.HasValue ?
                new ObjectParameter("IdPeriodo", idPeriodo) :
                new ObjectParameter("IdPeriodo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cerrar_periodo", idPeriodoParameter);
        }
    }
}
