//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_empleado_x_formulario
    {
        public int IdPeriodo { get; set; }
        public int Secuencia { get; set; }
        public decimal Idempleado { get; set; }
        public decimal Idempleado_evaluado { get; set; }
        public decimal IdFormulario { get; set; }
        public double ef_ponderacion { get; set; }
        public Nullable<double> ef_calificacion { get; set; }
        public Nullable<double> ef_calificacion_ponderacion { get; set; }
    
        public virtual enc_formulario enc_formulario { get; set; }
        public virtual rol_empleado rol_empleado { get; set; }
        public virtual rol_empleado rol_empleado1 { get; set; }
    }
}
