//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rol_empleado()
        {
            this.enc_resolucion_formulario = new HashSet<enc_resolucion_formulario>();
            this.rol_empleado_x_formulario = new HashSet<rol_empleado_x_formulario>();
            this.rol_empleado_x_formulario1 = new HashSet<rol_empleado_x_formulario>();
            this.enc_resolucion_calificacion = new HashSet<enc_resolucion_calificacion>();
        }
    
        public decimal IdEmpleado { get; set; }
        public string re_codigo { get; set; }
        public string re_apellidos { get; set; }
        public string re_nombres { get; set; }
        public string re_cedula { get; set; }
        public string re_correo { get; set; }
        public string re_telefonos { get; set; }
        public string re_direccion { get; set; }
        public int IdCargo { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enc_resolucion_formulario> enc_resolucion_formulario { get; set; }
        public virtual rol_cargo rol_cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_empleado_x_formulario> rol_empleado_x_formulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_empleado_x_formulario> rol_empleado_x_formulario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enc_resolucion_calificacion> enc_resolucion_calificacion { get; set; }
    }
}
