//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_periodo_evaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_periodo_evaluacion()
        {
            this.enc_formulario = new HashSet<enc_formulario>();
            this.enc_resolucion_formulario = new HashSet<enc_resolucion_formulario>();
            this.enc_resolucion_calificacion = new HashSet<enc_resolucion_calificacion>();
        }
    
        public int IdPeriodo { get; set; }
        public System.DateTime pe_fecha_ini { get; set; }
        public System.DateTime pe_fecha_fin { get; set; }
        public string pe_observacion { get; set; }
        public bool estado { get; set; }
        public bool estado_cierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enc_formulario> enc_formulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enc_resolucion_formulario> enc_resolucion_formulario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enc_resolucion_calificacion> enc_resolucion_calificacion { get; set; }
    }
}
