//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_parametros_correo
    {
        public int IdParametros { get; set; }
        public string ep_correo { get; set; }
        public string ep_contrasenia { get; set; }
        public int ep_puerto { get; set; }
        public bool ep_permite_sll { get; set; }
        public string ep_dominio { get; set; }
        public string ep_observacion { get; set; }
    }
}
