//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_reporte002
    {
        public decimal IdEmpleado { get; set; }
        public int IdPeriodo { get; set; }
        public string re_codigo_eva { get; set; }
        public string re_apellidos_eva { get; set; }
        public string re_nombres_eva { get; set; }
        public string re_cedula { get; set; }
        public string re_codigo { get; set; }
        public string re_apellidos { get; set; }
        public string re_nombres { get; set; }
        public string ef_descripcion { get; set; }
        public string ep_descripcion { get; set; }
        public Nullable<double> re_ponderacion { get; set; }
        public double ep_ponderacion { get; set; }
        public Nullable<double> Ponderacion_x_pregunta { get; set; }
        public double ef_ponderacion { get; set; }
        public Nullable<double> ef_calificacion { get; set; }
        public Nullable<double> ef_calificacion_ponderacion { get; set; }
        public decimal Idempleado_evaluado { get; set; }
        public double Calificacion { get; set; }
        public bool factor_cumplimiento { get; set; }
        public double calificacion_final { get; set; }
    }
}
